packages:
  - apps/*
  - packages/*
minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1139.0'
  - '@aws-sdk/lib-storage@3.1139.0'
  - '@sentry/browser-utils@11.0.0'
  - '@sentry/browser@11.0.0'
  - '@sentry/bundler-plugins@11.0.0'
  - '@sentry/core@11.0.0'
  - '@sentry/feedback@11.0.0'
  - '@sentry/nextjs@11.0.0'
  - '@sentry/node@11.0.0'
  - '@sentry/opentelemetry@11.0.0'
  - '@sentry/react@11.0.0'
  - '@sentry/replay-canvas@11.0.0'
  - '@sentry/replay@11.0.0'
  - '@sentry/server-runtime-injection@11.0.0'
  - '@sentry/server-utils@11.0.0'
  - '@sentry/vercel-edge@11.0.0'
  - '@supabase/auth-js@2.117.1'
  - '@supabase/functions-js@2.117.1'
  - '@supabase/postgrest-js@2.117.1'
  - '@supabase/realtime-js@2.117.1'
  - '@supabase/storage-js@2.117.1'
  - '@supabase/supabase-js@2.117.1'
  - batch-cluster@19.3.2
  - exiftool-vendored@38.1.2
onlyBuiltDependencies:
  - sharp
  - supabase
  - esbuild
